name: TestMioRepo
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
      - name: JavaInstall
        uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 11
      - name: Build
        run: ./gradlew check

